.web-api-setup-script: &web-api-setup-script
  - cd web-api
  - pip install -r requirements.txt

test-web-api:
  image: python:3.11
  stage: test
  before_script: *web-api-setup-script
  script: python3 -m pytest -s
